Controllers/CategoryController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using otce_project_final.Data;
using otce_project_final.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace otce_project_final.Controllers
{
    [Authorize(Roles = GlobalConstants.AdminRole)]
    public class CategoryController : Controller
    {
        private readonly AppDbContext _rdb;

        public CategoryController(AppDbContext db)
        {
            _rdb = db;
        }

        public IActionResult Index()
        {
            IEnumerable<Category> list = _rdb.Category;
            return View(list);
        }

        /* SHOW - create a new category page */
        public IActionResult Create()
        {
            return View();
        }


        /* SHOW - update an existing category page */
        public IActionResult Edit(int? id)
        {
            if( id == 0 || id == null ) { return NotFound();  }

            var category = _rdb.Category.Find(id);
            if( category == null ) { return NotFound();  }

            return View(category);
        }

        /* POST - CREATE new category to db */
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Category cat)
        {
            _rdb.Category.Add(cat);
            _rdb.SaveChanges();
            return RedirectToAction("Index");
        }

        /* POST - EDIT existing category */
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Category cat)
        {
            if(ModelState.IsValid)
            {
                _rdb.Category.Update(cat);
                _rdb.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(cat);
        }

        /* SHOW - delete page */
        public IActionResult Delete(int? id)
        {
            if( id == 0 || id == null) { return NotFound(); }

            var category = _rdb.Category.Find(id);
            if (category == null) { return NotFound(); }

            return View(category);
        }

        /* POST - delete category from db */
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteCategory(int? id)
        {
            var cat = _rdb.Category.Find(id);
            if (cat == null) { return NotFound(); }

            _rdb.Category.Remove(cat);
            _rdb.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Controllers/DrinksController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using otce_project_final.Data;
using otce_project_final.Models;
using otce_project_final.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace otce_project_final.Controllers
{
    public class DrinksController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/FoodController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using otce_project_final.Data;
using otce_project_final.Models;
using otce_project_final.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace otce_project_final.Controllers
{
    public class FoodController : Controller
    {
        private readonly ILogger<FoodController> _logger;
        private readonly AppDbContext _rdb; 
        public FoodController(ILogger<FoodController> logger, AppDbContext rdb)
        {
            _logger = logger;
            _rdb = rdb;
        }

        public IActionResult Index()
        {
            HomeVM hvm = new HomeVM()
            {
                Products = _rdb.Product.Include(c => c.Category),
                Categories = _rdb.Category
            };
            return View(hvm);
        }
    }
}

Controllers/ProductController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using otce_project_final.Data;
using otce_project_final.Models;
using otce_project_final.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace otce_project_final.Controllers
{
    [Authorize(Roles = GlobalConstants.AdminRole)]
    public class ProductController : Controller
    {
        private readonly IWebHostEnvironment _webHostEnv;
        private readonly AppDbContext _rdb;

        public ProductController(AppDbContext db, IWebHostEnvironment webHostEnv)
        {
            _rdb = db;
            _webHostEnv = webHostEnv;
        }

        /* Category Mainpage - GET */
        public IActionResult Index()
        {
            /* enumerable method - use eager loading instead 
            IEnumerable<Product> list = _rdb.Product;

            foreach(var product in list)
            {
                product.Category = _rdb.Category.FirstOrDefault(c => c.Id == product.CategoryId);
            }; */

            IEnumerable<Product> list = _rdb.Product.Include(c => c.Category);
            return View(list);
        }

        /* CreateUpdate Product - GET */
        public IActionResult CreateUpdate(int? id)
        {
            ProductVM pvm = new ProductVM()
            {
                Product = new Product(),
                CategorySelector = _rdb.Category.Select(c => new SelectListItem
                {
                    Text = c.Name,
                    Value = c.Id.ToString()
                })
            };

            if( id == null)
            {
                /* Create New Product */
                return View(pvm);
            }
            else
            {
                pvm.Product = _rdb.Product.Find(id);

                if(pvm.Product==null) { return NotFound();  }
                return View(pvm);
            }
        }        

        /* CreateUpdate Product - POST */
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult CreateUpdate(ProductVM pvm)
        {
            if( ModelState.IsValid )
            {
                var files = HttpContext.Request.Form.Files;

                // path to wwwroot to grab images folder
                string DocumentRoot = _webHostEnv.WebRootPath;

                if( pvm.Product.Id == 0 )
                {
                    /* IF-CASE: Creating */

                    // relative path to product images
                    string uploadPath = DocumentRoot + GlobalConstants.ImagePath;
                    string fName = Guid.NewGuid().ToString();
                    string fType = Path.GetExtension(files[0].FileName);

                    using (var fStream = new FileStream( Path.Combine(uploadPath, fName + fType), FileMode.Create ))
                    {
                        files[0].CopyTo(fStream);
                    }

                    //pvm.Product.Image = uploadPath + fName + fType;
                    pvm.Product.Image = fName + fType;

                    _rdb.Product.Add(pvm.Product);
                }
                else
                {
                    /* IF-CASE: Updating */

                    // use AsNoTracking to prevent duplicate tracking on local Product vs ProductViewModel
                    var product = _rdb.Product.AsNoTracking().FirstOrDefault(m => m.Id == pvm.Product.Id);

                    if( files.Count > 0)
                    {
                        // relative path to product images
                        string uploadPath = DocumentRoot + GlobalConstants.ImagePath;
                        string fName = Guid.NewGuid().ToString();
                        string fType = Path.GetExtension(files[0].FileName);

                        var fOld = Path.Combine(uploadPath, product.Image);

                        // delete existing image
                        if( System.IO.File.Exists(fOld))
                        {
                            System.IO.File.Delete(fOld);
                        }

                        // update to new image
                        using (var fStream = new FileStream( Path.Combine(uploadPath, fName + fType), FileMode.Create ))
                        {
                            files[0].CopyTo(fStream);
                        }

                        pvm.Product.Image = fName + fType;
                    }
                    else
                    {
                        pvm.Product.Image = product.Image;
                    }

                    _rdb.Product.Update(pvm.Product);
                }

                _rdb.SaveChanges();
                return RedirectToAction("Index");
            }

            // if model state was invalid, make sure to still initialize category dropdown
            pvm.CategorySelector = _rdb.Category.Select(c => new SelectListItem
            {
                Text = c.Name,
                Value = c.Id.ToString()
            });

            return View(pvm);
        }
    
        /* Delete Product - GET */
        public IActionResult Delete(int? id)
        {
            // semi-validate ID
            if( id == 0 || id == null) { return NotFound(); }

            // eager load category
            Product product = _rdb.Product.Include(c => c.Category).FirstOrDefault(i => i.Id == id); 

            if (product == null) { return NotFound(); }

            return View(product);
        }

        /* Delete Product - POST */
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteProduct(int? id)
        {
            var product = _rdb.Product.Find(id);
            if (product == null) { return NotFound(); }

            // relative path to product images
            string uploadPath = _webHostEnv.WebRootPath + GlobalConstants.ImagePath;

            var mFile = Path.Combine(uploadPath, product.Image);

            // delete existing image
            if( System.IO.File.Exists(mFile))
            {
                System.IO.File.Delete(mFile);
            }

            _rdb.Product.Remove(product);
            _rdb.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - OTCE</title>
    <!--
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    -->
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/font-awesome/css/all.css" />
    <link rel="stylesheet" href="~/css/bootstrap-theme.min.css" />
    <link rel="stylesheet" href="~/css/otce.css" />
</head>
<body id="body-otce">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-primary border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand font-weight-bold text-white badge bg-otce" asp-area="" asp-controller="Home" asp-action="Index">Olde Towne<br /><small>Espresso &amp; Cafe</small></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Food" asp-action="Index">Food</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Drinks" asp-action="Index">Drinks</a>
                        </li>
                        @if (User.IsInRole(GlobalConstants.AdminRole))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Product Managment
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" asp-area="" asp-controller="Category" asp-action="Index">Categories</a>
                                    <a class="dropdown-item" asp-area="" asp-controller="Product" asp-action="Index">Products</a>
                                </div>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Olde Towne Espresso &amp; Coffee
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/otce.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_ProductListItem.cshtml
@model otce_project_final.Models.Product

<!-- Bootstrap Card-->
<div class="col-4 mb-4 filter @Model.Category.Name.Replace(' ','-')">
    <div class="card h-100">
        <div class="img-magnifier-container">
            <img src="@GlobalConstants.ImagePath@Model.Image" width="340" height="300" class="card-img-top img-zoom"/>
        </div>
        <div class="card-body">
            <h4 class="card-title mb-0">@Model.Name</h4>
            <p class="text-secondary font-italic">@Model.Category.Name</p>
            <p class="card-text card-fixed-height">@Model.Description</p>
            <h3>
                <span class="badge bg-primary text-white w-100 p-2">$@Model.Price</span>
            </h3>
        </div>
    </div>
</div>